[package]
name = "cleam"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
aws-sdk-cloudwatchlogs = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
chrono = "0.4"
